baseURL = 'https://mzo.kuku9.net/namachi'
languageCode = 'ja-JP'

disableKinds = ["taxonomy", "sitemap", "RSS"]
disableSitemap = true

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ja]
    languageCode = "ja"
    contentDir = "content/ja"
    title = "生知能論"
    [languages.ja.params]
        subtitle = "AIはあなたを自由にするか？"
        description = "人工知能と人間の知能の類似性と違いを明示した上で、人工知能をこれまでのテクノロジーの発展の流れの中に位置づけることで、AIが社会にどのようなインパクトをもたらすかを検討します。"
        cardFilename = "card_image.png"

  [languages.en]
    languageCode = "en"
    contentDir = "content/en"
    title = "Nama Intelligence"
    [languages.en.params]
        subtitle = "Will A.I. set you free?"
        description = "After explicitly identifying the similarities and differences between artificial intelligence(A.I.) and human intelligence, we will examine the impact of A.I. on society by situating A.I. within the flow of technological development to date."
        cardFilename = "card_image.png"
    [languages.en.markup.goldmark.extensions.cjk]
        enable = false
    [languages.en.markup.goldmark.renderer]
      unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'css3draft'

    [markup.goldmark.renderer]
      unsafe = true
